# --- SERVEUR 1 : Site Principal ---
server {
    listen 8080;
    host 127.0.0.1;
    server_name localhost;
    root ./www;
    index index.html;
    client_max_body_size 10; # 10MB

    error_page 404 www/errorPages/404bis.html;

    location / {
        methods GET POST;
        autoindex on;
    }

    location /upload {
        methods POST GET DELETE;
        upload_store ./www/upload;
        autoindex on;
    }

    location /cgi-bin {
        methods GET POST DELETE;
        cgi_enabled on;
        cgi_info .py /usr/bin/python3;
        cgi_info .sh /bin/bash;
    }

    location /old-site {
        return 301 /testRedir.html;
    }
}

# --- SERVEUR 2 : Second site sur un port différent ---
server {
    listen 9090;
    host 127.0.0.1;
    server_name second_site;
    root ./www;
    index index.html;

    location / {
        methods GET;
        autoindex off;
    }
}

# --- SERVEUR 3 : Virtual Host (Même port, Nom différent) ---
# Serveur check le header "Host" de la requête HTTP 
# pour savoir s'il utilise le Serveur 1 ou le Serveur 3.
server {
    listen 8080;
    host 127.0.0.1;
    server_name vhost.com;
    root ./www/vhost;
    
    location / {
        methods GET;
        index vhost.html;
    }
}

server {
    listen 8081;
    host 127.0.0.1;
    server_name localhost;
    root ./www;
    index index.html;
    client_max_body_size 1000000000; # 10MB

    error_page 404 /errors/404.html;

    location / {
        methods GET POST;
        autoindex on;
    }

    location /upload {
        methods POST GET DELETE;
        upload_store ./www/upload;
    }

    location /cgi-bin {
        methods GET POST DELETE;
        cgi_enabled on;
        cgi_info .py /usr/bin/python3;
        cgi_info .sh /bin/bash;
    }

    location /old-site {
        return 301 /;
    }
}

server {
    listen 8082;
    host 127.0.0.1;
    server_name localhost;
    root ./www;
    index index.html;
    client_max_body_size 1000; # 10MB

    error_page 404 /errors/404.html;

    location / {
        methods GET POST;
        autoindex on;
    }

    location /upload {
        methods POST GET DELETE;
        upload_store ./www/upload;
    }

    location /cgi-bin {
        methods GET POST DELETE;
        cgi_enabled on;
        cgi_info .py /usr/bin/python3;
        cgi_info .sh /bin/bash;
    }

    location /old-site {
        return 301 /;
    }
}

server {
    listen 8083;
    host 127.0.0.1;
    server_name localhost;
    root ./www;
    index index.html;
    client_max_body_size 1000; # 10MB

    location / {
        methods GET;
        autoindex on;
    }

    location /upload {
        methods POST;
        upload_store ./www/upload;
    }

    location /cgi-bin {
        methods GET POST DELETE;
        cgi_enabled on;
        cgi_info .py /usr/bin/python3;
        cgi_info .sh /bin/bash;
    }

    location /old-site {
        return 301 /;
    }
}

server {
    listen 8084;
    host 127.0.0.1;
    server_name localhost;
    root ./www;
    index index.html;
    client_max_body_size 1000; # 10MB

    error_page 404 /errors/404.html;

    location / {
        methods GET POST;
        autoindex on;
    }

    location /upload {
        methods DELETE;
        upload_store ./www/upload;
    }

    location /cgi-bin {
        methods GET POST DELETE;
        cgi_enabled on;
        cgi_info .py /usr/bin/python3;
        cgi_info .sh /bin/bash;
    }

    location /old-site {
        return 301 /;
    }
}